config/routes.rb
SocialApp::Application.routes.draw do
resources :users
root :to => 'static_pages#home'
  
  match '/home',      to: 'static_pages#home'

  match '/signup',    to: 'users#new'

  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
 

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :email, :name, :password, :password_confirmation
has_secure_password

before_save { |user| user.email = user.email.downcase }

validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  # after_validation { self.errors.messages.delete(:password_digest) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 #Returns base title on a per page basis. 
  def full_title(page_title) 
    base_title = 'FratChat'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"  
    end  
  end
end   

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://github.com/obedeugene/social_app">FratChat</a>
    by Obed Eugene
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FratChat", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Help",   help_path %></li>
		  <li><%= link_to "signin", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
This is a FratChat build in Ruby on Rails by <a href="http://github.com/obedeugene">Obed Eugene</a>
</p>
 

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
This is a FratChat build in Ruby on Rails by <a href="http://github.com/obedeugene">Obed Eugene</a>
</p>
 

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
For Help, contact <a href="http://github.com/obedeugene">Obed Eugene</a>.</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

<h1>Welcome to FratChat</h1>
<p>
	This is a app for Fraternities and Sororities to chat 
</p>	

<%=	link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>